// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDsMessage = "ds_message"

// DsMessage mapped from table <ds_message>
type DsMessage struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID     string    `gorm:"column:app_id;not null" json:"app_id"`
	TenantID  string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UnionID   string    `gorm:"column:union_id;not null" json:"union_id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	SendType  string    `gorm:"column:send_type;not null" json:"send_type"`
	MessageID string    `gorm:"column:message_id;not null" json:"message_id"`
	RootID    string    `gorm:"column:root_id" json:"root_id"`
	ParentID  string    `gorm:"column:parent_id" json:"parent_id"`
	ChatID    string    `gorm:"column:chat_id;not null" json:"chat_id"`
	ChatType  string    `gorm:"column:chat_type;not null" json:"chat_type"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	EventJSON string    `gorm:"column:event_json" json:"event_json"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName DsMessage's table name
func (*DsMessage) TableName() string {
	return TableNameDsMessage
}
