# 第一步：基础镜像，设置时区
FROM alpine:3.18 AS base

# 安装 tzdata 包
RUN apk add --no-cache tzdata

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY user-service /app/user-service
COPY *.yaml /app/
COPY entrypoint.sh /app/entrypoint.sh

WORKDIR /app
RUN chmod +x /app/entrypoint.sh
CMD ["./entrypoint.sh"]

